// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  quote: dynamic(() => import("./Quote")),
  split_image_text: dynamic(() => import("./SplitImageText")),
  text: dynamic(() => import("./Text")),
  text_slice: dynamic(() => import("./TextSlice")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
